server:
  port: 8081
spring:
  application:
    name: "Loan"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
adapters:
  r2dbc:
    host: localhost
    port: 5432
    database: micro_loan
    schema: public
    username: postgres
    password: 1234
logging:
  level:
    root: INFO
    co.com.pragma: TRACE